import type { TimelinePostData } from "@/components/TimelinePost/types";

export const MOCK_POSTS: TimelinePostData[] = [
  {
    id: "post-001",
    userId: "user-001",
    name: "Yapper Team",
    handle: "@yapper",
    avatarUrl: "https://placehold.co/96x96/png",
    message:
      "This is first look at the Yapper timeline. Sharing updates, photos, and quick reactions. All coming soon.",
    imageUrl: "https://placehold.co/640x360/png",
    likes: 128,
    replies: 24,
    reposts: 12,
  },
  {
    id: "post-002",
    userId: "user-002",
    name: "Tyson Not Fury",
    handle: "@notFury",
    avatarUrl: "https://placehold.co/96x96/png",
    message: "Retired.",
    likes: 56,
    replies: 8,
    reposts: 4,
  },
  {
    id: "post-003",
    userId: "user-003",
    name: "John Wick",
    handle: "@buildwithwick",
    avatarUrl: "https://placehold.co/96x96/png",
    message: "I'm back. Again.",
    imageUrl: "https://placehold.co/640x360/png",
    likes: 92,
    replies: 15,
    reposts: 7,
  },
  {
    id: "post-004",
    userId: "user-004",
    name: "John Rambo",
    handle: "@rambocodes",
    avatarUrl: "https://placehold.co/96x96/png",
    message: "I'm not too old for it. Yet.",
    likes: 41,
    replies: 6,
    reposts: 3,
  },
  {
    id: "post-005",
    userId: "user-005",
    name: "Yapper Community",
    handle: "@yappercommunity",
    avatarUrl: "https://placehold.co/96x96/png",
    message:
      "Share your favorite timeline layout ideas. We are collecting inspirations for the inevitable launch.",
    imageUrl: "https://placehold.co/640x360/png",
    likes: 77,
    replies: 19,
    reposts: 11,
  },
];
